import type { AudioVisualHomePayload, AudioVisualItem } from '../../types/audioVisual';

const churchImage = '/images/church-front-left-1920.jpg';

export const fallbackMediaItems: AudioVisualItem[] = [
  {
    title: 'Walking in Faith, Not by Sight',
    slug: 'walking-in-faith-not-by-sight',
    description: 'What happens when faith must walk before sight?',
    descriptionExcerpt: 'What happens when faith must walk before sight?',
    thumbnailUrl: churchImage,
    mediaType: 'sermon',
    mediaTypeLabel: 'Sermon',
    durationSeconds: 1080,
    publishedAt: '2026-05-12',
    speaker: 'Rev. Harun Njuguna',
    scriptureReference: '2 Corinthians 5:7',
    categories: [{ name: 'Sermons', slug: 'sermons' }],
    collections: [{ name: 'Featured', slug: 'featured' }],
    series: { name: 'Walking in Faith', slug: 'walking-in-faith' },
  },
  {
    title: 'Grace That Saves',
    slug: 'grace-that-saves',
    description: 'The transforming power of grace and surrender.',
    descriptionExcerpt: 'The transforming power of grace and surrender.',
    thumbnailUrl: churchImage,
    mediaType: 'sermon',
    mediaTypeLabel: 'Sermon',
    durationSeconds: 1463,
    publishedAt: '2026-05-05',
    speaker: 'A.I.C Njoro Town',
    scriptureReference: 'Ephesians 2:8',
    categories: [{ name: 'Sermons', slug: 'sermons' }],
    collections: [{ name: 'Latest Sermons', slug: 'latest-sermons' }],
    series: { name: 'Grace for the Journey', slug: 'grace-for-the-journey' },
  },
  {
    title: 'Joy in the Journey',
    slug: 'joy-in-the-journey',
    description: 'Finding peace in the middle of uncertainty.',
    descriptionExcerpt: 'Finding peace in the middle of uncertainty.',
    thumbnailUrl: churchImage,
    mediaType: 'teaching',
    mediaTypeLabel: 'Teaching',
    durationSeconds: 2110,
    publishedAt: '2026-04-28',
    speaker: 'A.I.C Njoro Town',
    scriptureReference: 'Philippians 4:4',
    categories: [{ name: 'Teaching', slug: 'teaching' }],
    collections: [{ name: 'Latest', slug: 'latest' }],
    series: { name: 'Life in Christ', slug: 'life-in-christ' },
  },
  {
    title: 'Sunday Highlights',
    slug: 'sunday-highlights',
    description: 'A moment of worship from our Sunday gathering.',
    descriptionExcerpt: 'A moment of worship from our Sunday gathering.',
    thumbnailUrl: churchImage,
    mediaType: 'short',
    mediaTypeLabel: 'Short',
    durationSeconds: 58,
    publishedAt: '2026-04-21',
    speaker: 'Worship & Music',
    categories: [{ name: 'Worship', slug: 'worship' }],
    collections: [{ name: 'Shorts & Highlights', slug: 'shorts-highlights' }],
    series: null,
  },
  {
    title: 'Word of Encouragement',
    slug: 'word-of-encouragement',
    description: 'A reminder that God is still present in the waiting.',
    descriptionExcerpt: 'A reminder that God is still present in the waiting.',
    thumbnailUrl: churchImage,
    mediaType: 'short',
    mediaTypeLabel: 'Short',
    durationSeconds: 45,
    publishedAt: '2026-04-14',
    speaker: 'A.I.C Njoro Town',
    scriptureReference: 'Psalm 27:14',
    categories: [{ name: 'Devotional', slug: 'devotional' }],
    collections: [{ name: 'Shorts & Highlights', slug: 'shorts-highlights' }],
    series: null,
  },
];

export const fallbackMediaHome: AudioVisualHomePayload = {
  generatedAt: new Date().toISOString(),
  hero: fallbackMediaItems[0],
  live: {
    ctaLabel: 'Watch live',
    item: {
      ...fallbackMediaItems[0],
      title: 'Sunday Service Livestream',
      slug: 'sunday-service-livestream',
      description: 'Join the church family in worship, prayer, and the Word.',
      descriptionExcerpt: 'Join the church family in worship, prayer, and the Word.',
      mediaType: 'livestream',
      mediaTypeLabel: 'Livestream',
      liveStatus: 'upcoming',
    },
  },
  rails: [
    { key: 'featured', title: 'Featured Sermons', items: fallbackMediaItems.slice(0, 3) },
    { key: 'series', title: 'Sermon Series', items: fallbackMediaItems.slice(0, 3) },
    { key: 'latest', title: 'Latest Sermons', items: fallbackMediaItems.slice(0, 4) },
    { key: 'shorts', title: 'Shorts & Highlights', items: fallbackMediaItems.slice(3) },
  ],
};
